### ISSUE TITLE
Esc should close the output panel

### ISSUE THREAD

**Issue by braver** [noseglid/atom-build#123]
It's a convention in Atom that `esc` closes a panel. In this package however, it clears the build output. Which I end up doing a lot for no reason :wink: I bet there's a keyboard shortcut for closing the panel, and of course I can overrule it in my personal keymap, but there is something to be said for sticking to the convention. 
So.. I'm just putting it out there I guess.

**Comment by noseglid** [comment]
I looked closer at this. `build` works in this manner:

  * if `Panel Visibility` is set to `Toggle` it will abort the build cleanly (by sending SIGTERM) the **first** time `Esc` is pressed, forcefully close the build process the **second** time (`kill -9` or windows equivalent), and hide the build panel on the **third** press of `Esc`
  * if `Panel Visibility` is `Show on Error` it will only be visible when an error has occurred, and pressing `Esc` will close it.
  * If `Panel Visibility` is `Keep Visible` it will work the same as if it is `Toggle` - except that it will clear the window rather than closing it on the **third** press of `Esc`.
  * If it is `Hidden` it is always closed.

Do you expect any different behaviour?

**Comment by braver** [comment]
Ah, that helps. I'm coming from Sublime, where by default the build output is visible until you close the panel with ESC. Also, some of the build tools I'm using may have multiple steps where something in the middle may fail. I want to keep the output visible because I can't rely on the "build failed".
So, I'm looking at the keep visible mode not to have that panel take up space all the time, but to have it stick around until I close it. As such, I don't see the use of clearing the output (I imagine it clears before the next build). But I do want closing the panel to be easy and ESC is the easiest way to do that. I think you're envisioning the use of the keep visible mode differently, and the behavior I'm looking for is just not available as an option.

**Comment by noseglid** [comment]
I have to agree with you that there really is no reason to clear the build panel of the output unless it was to make room for a new build.

I'm not sure whether or not escape should close the panel though if `Panel Visibility` is set to keep visible. If it does, it would work exactly as `Toggle`, except that successful builds would stay open as well as failed builds.

**Comment by braver** [comment]
> except that successful builds would stay open as well as failed builds.

Which is exactly what I'm looking for :) , but I would agree that repurposing "keep visible" for that use is perhaps not the way to go.

**Comment by noseglid** [comment]
I'll close this out for now. I am open to reconsidering this if it gets enough traction.
