### ISSUE TITLE
Add Service API, Allowing Registration Of Grammar-Specific Builders

### ISSUE THREAD

**Issue by joefitzgerald** [noseglid/atom-build#124]
It would be really nice to add a services API to this package, so that support for each "kind" of builder can be externalized into packages that others can contribute to. This would be similar in concept to the way autocomplete-plus and linter work.

For example, my package – [go-plus](https://github.com/joefitzgerald/go-plus) currently builds go apps. It currently only supports one strategy for building go apps - using the `go` tool - a part of the go runtime installation. I plan to modify the package to support multiple builders - the selection of which would be dependent on the directory for the current file:

* `go build`
* [`gb`](https://github.com/constabulary/gb)
* [`gox`](https://github.com/mitchellh/gox)
* [`goxc`](https://github.com/laher/goxc)

All are valid builders for go code. This means I need some logic to select the correct builder for a given project (although I will accept the responsibility of resolving "use this go builder" once the more general problem of "this is a go file or a go project" has been resolved). Thus, an ideal services API would allow:

1. When a file opens or a project root changes, call a function of mine asking "can you build this project root or currently open file?". A go builder would say "yes" if the current file has the `.go` extension, the current file's grammar is `language-go`, or the current project folder has the "traits" of a go source directory (i.e. it is within `$GOPATH/src/`, it contains `.go` files, or a subdirectory contains `.go` files).
1. Allow registration of a function to be called when the user asks to build a file or a project. This function would be supplied with context associated with the build - the current project / file path, other relevant information. For the go builder, this function could resolve the complexity of choosing between `go build`, `gb`, `gox`, or `goxc`. 
1. A way to prioritize my `I can build this project` function such that more general purpose builders don't win when a more specific builder is available. This will probably also need some configuration-file based override, which you have the foundations available for already.

Does this make sense?

**Comment by noseglid** [comment]
I have been toying with the idea of using the [service API](https://atom.io/docs/latest/behind-atom-interacting-with-packages-via-services) to allow other to provide build tools for the package. Up until recently it felt quite silly since the build tools are only a few lines. This has changed though and some tools are quite extensible (the `gulp` tool for instance extracts all targets and provide a list of available targets).

The API you're describing is very similar to how the core build functionality works with the [tools](https://github.com/noseglid/atom-build/tree/master/lib/tools).

Designing APIs are difficult and I would love some collaboration to get a neat interface set up.

**Comment by noseglid** [comment]
A PR for this is available in #139 .

**Comment by noseglid** [comment]
#139 is now merged and the service module is available.
