### ISSUE TITLE
Feature suggestion - auto-extract Make commands from project makefile

### ISSUE THREAD

**Issue by mangecoeur** [noseglid/atom-build#140]
Basically the idea is to include the functionality of the MakeCommands package from ST( https://bitbucket.org/klorenz/makecommands/src/c373e0252dd2?at=default): 

> If you are editing a file, which has a Makefile on same or higher level in directory structure, targets from it are automatically made available as commands. If there is a target "test", then there will be created command ":make test".

**Comment by noseglid** [comment]
I actually fiddled quite a bit with this when implementing build targets. However, it turned out quite difficult to extract the targets from a Makefile.

I wanted to use the built-in functionality of make to (`-p`) to get the targets. However, it returned a butt load of targets, and a large amount are automatically generated by make and are probably not of interest for the user.

It would be possible to match the `Makefile` with some regexp, but that would make it difficult to get it to work with the `include` directive allowed in `GNU Make`.

Since I didn't find a complete enough solution, I just decided to skip it. Looking at the link you provided, it appears as you have to make a phony target `.SUBMLIME_TARGETS` and list the targets you want Sublime to see. Awkward at best...

**Comment by mangecoeur** [comment]
@noseglid The `.SUBLIME_TARGETS` is only if you want to specify a subset of targets if there are too many:

> There may be produced too many targets from your makefiles and you only use a subset of the targets. Then you can create a special target .SUBLIME_TARGETS

It's true the ST plugin doesn't consider Make `include` commands - it just regexes for targets within the current folders. That doesn't make is useless though - I think it would still be a nice addition even with this limitation - there are plenty of  makefiles with no `include`s . In the long run it should be possible to add support for includes.

**Comment by noseglid** [comment]
I'm in the process of moving tools to separate projects. I'm moving this to [noseglid/atom-build-make](https://github.com/noseglid/atom-build-make).
