### ISSUE TITLE
Can't figure out how to parse full path to something "build" will recognize.

### ISSUE THREAD

**Issue by hohonuuli** [noseglid/atom-build#152]
I'm using maven/sbt/javac to compile files via build. These tools output a full path to the file but build wants a path relative to the project root. Is there a way to pass a full path (relative to filesystem root) or a way to escape {PROJECT_PATH} so the regex can use it? Here's an example ...

__Output from Maven__
`[error] /Users/brian/workspace/deepseaguide/dsg-webapp/src/main/scala/org/mbari/dsg/transforms/TaxaTreeBuilder2.scala:100: recursive value selector needs type`

__Regex in .atom-build.json__

`"errorMatch": "^\\[error\\] (?<file>.*\/\\w+\\.(scala|java)):(?<line>\\d+).+$"`

I _think_ this is regex is correct, sorry, I don't know how to debug it in atom. This should be giving the following:

```
file	[8-117]	`/Users/brian/workspace/deepseaguide/dsg-webapp/src/main/scala/org/mbari/dsg/transforms/TaxaTreeBuilder2.scala`
2.	[112-117]	`scala`
line	[118-121]	`100`
```
I tried using to regex below to get a path relative to the  project root:

`"errorMatch": "^\\[error\\] {PROJECT_PATH}\/(?<file>.*\/\\w+\\.(scala|java)):(?<line>\\d+).+$"`

But since PROJECT_PATH's `/` characters aren't escaped, It's not working. Any idea, workarounds or suggestions?

Thanks!

**Comment by noseglid** [comment]
The `?<file>` thingie supports both absolute and relative paths, so that's likely not it. I don't think your regex matches the output. I haven't tested, but since `.*` [is greedy](http://www.regular-expressions.info/repeat.html#greedy) I would assume that it matches the whole line.
The circumflex (`^` could also be the culprit if your output doesn't start with the mentioned output.

Try this regex instead (untested, might need a tweak): `\[error\] (?<file>[^:]+):(?<line>\d+)`

**Comment by hohonuuli** [comment]
Sweet! That worked. Just for the record, here's my `.atom-build.json` file for folks who want to add Maven (or SBT) to _Build_:

```
{
  "cmd": "mvn",
  "args": [ "compile", "-Dmaven.test.skip=true" ],
  "sh": true,
  "cwd": "{PROJECT_PATH}",
  "env": {
    "JAVA_OPTS": "-Duser.timezone=UTC"
  },
  "errorMatch": "\\[error\\] (?<file>[^:]+):(?<line>\\d+)"
}

```
