### ISSUE TITLE
Build: Select active target no-more read gulpfile correctly

### ISSUE THREAD

**Issue by npirotte** [noseglid/atom-build#157]
Hi, 

Since last update (0.44.0) I can't chose a specific task from my gulpfile, the "select active target" command only output the Default task in the task list.

**Comment by noseglid** [comment]
Hmm, I saw some issues with this and had to disable one test due to it. It works on my local environment but I guess something is fishy here. What OS are you on? What version of gulp do you have?

**Comment by mw8020** [comment]
Hi, also getting this also since last update. After running 'Build select active target':
Message: Task 'default' is not in your gulpfile
OS: Windows 7
Gulp: 3.9.0

Also not sure if you wanted this but here's a the contents of my gulpfile.js (which is in project root folder):

// this runs a local server with liveload function
var gulp = require('gulp');
var webserver = require('gulp-webserver');

gulp.task('webserver', function() {
  gulp.src('./')
    .pipe(webserver({
      livereload: true,
      directoryListing: true,
      open: true,
      port: '3000', // nomimal port to run server on     
    }));
});

Need any more info let me know ;)
