### ISSUE TITLE
Select Active Target hard to reach on Ubuntu: Ctrl-alt-T displays the terminal on all versions of Ubuntu.

### ISSUE THREAD

**Issue by Reyncor** [noseglid/atom-build#163]
What can I do? For some reason atom build is not switching build targets when I have a file from another project open... always remembering the first project I built... not the one I'm on. I can't seem to switch the target. And ctrl+alt+T is a holy shortcut in Ubuntu which I love.

Is there a way to select the active target based on the file I have open?
Or at least change the shortcut on linux.

**Comment by noseglid** [comment]
You can change the keybinding to whatever you want globally via the keymap settings:
Press `ctrl-alt-p`, type `open your keymap`. Add something like: 

```coffeescript
  "atom-workspace": 
    "ctrl-alt-t": "build:select-active-target"
```

And substitute `ctrl-alt-t` with whatever you want.

You could also assign a custom keymap to separate builds in the custom build file configuration, key `keymap`.

**Comment by Reyncor** [comment]
Perfect... made it be Ctrl-Alt-Shift-B

Still think it should be the default on at least Linux.

Thank you! ( btw you meant "Press ctrl-shift-p" )

**Comment by Reyncor** [comment]
Almost forgot.... This wouldn't even be necessary if the Active Target would auto switch based on which project the currently highlighted file was from. Is there a way to do that?

**Comment by noseglid** [comment]
Do you mean when it's using multiple project folders in one Atom window? If so, I've been meaning to change the behavior there so that it will remember which target was selected per project, and if any file in that project is currently active, it will run that target. Right now it's kind of silly that it builds `Project A` even if you're currently working in `Project B` just because you happened to build that last.

**Comment by Reyncor** [comment]
Exactly my point... Though pressing a 4 key shortcut isn't horrible for now... Thank you.
