### ISSUE TITLE
When using .atom-build.json extra target names are not processed properly

### ISSUE THREAD

**Issue by guysherman** [noseglid/atom-build#164]
Specify a file like the following:

{
  "cmd": "./waf",
  "name": "Build",
  "sh": "true",
  "targets" : [
      {
          "cmd": "./waf configure",
          "name": "Configure",
          "sh": "true"
      }
  ]
}

When you hit Ctrl+Alt+t you get two entries [ 'Custom: Build', 'Custom: 0'].

I've got a fix locally, will submit a PR in a moment.

**Comment by noseglid** [comment]
This is actually because `targets` should be an `Object`, where the key should be the name. Refer to [this section of the README](https://github.com/noseglid/atom-build#specifying-a-custom-build-command).

I agree that the statement _"all previous options are viable here except `targets`"_ is not entirely accurate as `name` can't be used either. The documentation should probably be updated to reflect that.

**Comment by guysherman** [comment]
Oh, ok, fair enough. Feel free to decline the PR.
