### ISSUE TITLE
Key binding is taken by built-in command

### ISSUE THREAD

**Issue by sryze** [noseglid/atom-build#168]
Ctrl+Alt+B seems to be assigned to `editor:move-to-previous-subword-boundary` by default. Is there any way to choose one over the other?

**Comment by noseglid** [comment]
I don't have that binding. Where does it come from?

You could set a keymap yourself, make sure it has the at least the same specificity as the built in. See https://discuss.atom.io/t/why-do-user-key-bindings-not-take-priority/11740

**Comment by Reyncor** [comment]
Same issue after updating to 1.0.8
http://i.imgur.com/UTK0p81.png

That said... none of the F5-F10 keys are taken.
For now ill try to map them to

Function	Shortcut Key
Build	Ctrl + F9
Compile current file	Ctrl + Shift + F9
Run	Ctrl + F10
Build and Run	F9
Rebuild	Ctrl + F11

Which is codeblocks default and doesn't conflict with any Atom core shortcuts.

**Comment by noseglid** [comment]
It appears as by default, `editor:move-to-previous-subword-boundary` is set to `alt-b` (See https://github.com/atom/atom/blob/master/keymaps/linux.cson#L98)

Is there something other that might have rebound the keys for you? Since you both have the same issue, it's likely to be another package. Would you mind pasting your installed packages (`apm list --installed`) ?

**Comment by noseglid** [comment]
Hmm, I think I found it. It appears to be because of https://github.com/atom/atom/blob/master/keymaps/emacs.cson#L9.

This change seems to have been made recently in atom/atom. I've opened an issue to see the developers take on this.
