### ISSUE TITLE
Remove error parser from atom-build package

### ISSUE THREAD

**Issue by X-Ryl669** [noseglid/atom-build#185]
Right now, the error parser included in atom-build package is specific to a language (which one, I don't know). We can specify the error parser's regex in our own build script, but doing so is tedious for each project we work on (specially if we don't need to change anything else for building).

Could it be possible that:
Solution 1:  Allow the parser to try on a successive error patterns by default. You can collect the 4 or 5 patterns from compilers and try then successively if the previous pattern does not match. 

Solution 2: Allow users to set global pattern in the atom's settings.

Thanks

**Comment by noseglid** [comment]
You could create a build tool using the service API. You can see how [it is done for Cargo](https://github.com/noseglid/atom-build-cargo).

Another approach could be to commit the `.atom-build.json` into the project (unless it contains environment specific entries). That way different developers on your projects don't need to manually sync the error matchers.

I do not want to specify a global error matcher because it doesn't make sense for most developers or most projects (which, nowadays, rarely is written in only one language).
