### ISSUE TITLE
[Feature Request] Ability to let providers specify the default active target.

### ISSUE THREAD

**Issue by xpol** [noseglid/atom-build#262]
Currently the default active target is set to be the first one in the target list.

What I need is to have my most used target (not the first one) set each time open the project.

I currently consider:

* Add a `active` filed to target. If set to `true` it will be one of the default active target candidates.
* A provider should only set one target to be active, If specify more than one the first with `active` set will be selected. 
* If multiple providers provides active target, the first one in the final targets list will be selected.
* If no targets with `active` set to `true`, the first target in the final targets list will be selected.

This should be simple to add. I'll add a PR later.

**Comment by noseglid** [comment]
I don't see how this is different from what exists today? The first target will be the prioritised one.
If multiple providers would specify the active target (and I bet every provider believes their targets are most important) it would still be "random" which target is the default one.

If you want a chance at being first, return it as the first target. Otherwise the user need to select by `select-active-target`.

**Comment by xpol** [comment]
I want my targets sort alphabetically, rather than by priorities.

eg:
![](https://raw.githubusercontent.com/xpol/build-cocos/master/images/targets.png)

Ant what I want to be selected is `Mac: Run without build`.

This does not change any thing for multiple providers.
But does provide more choice to single provider to have a way to make default target not in the first postion of list. And, for me, single provider is the most case.

**Comment by noseglid** [comment]
I don't think it makes much sense. For a build provider developer there's no telling whether or not you will be the only build provider, hence there's no telling if the `active` setting  will have any affect at all.
