### ISSUE TITLE
Targets list closes itself shortly after a completed build.

### ISSUE THREAD

**Issue by shakesoda** [noseglid/atom-build#300]
This comes up a lot when I have two build targets that I need to run.

1. ctrl-alt-t, build anything
2. ctrl-alt-t again within about a second of it finishing
3. targets list closes immediately.

**Comment by C-Bouthoorn** [comment]
Confirmed on Atom Beta

.atom-build.cson:
```
name: "sleep"
cmd: "sleep"
sh: true
args: [ "5" ]
```

Steps to reproduce:
1) Run build with `CTRL-ALT-T`,  `CTRL-ALT-T` + `Enter`, or `F9`
2) Open dialog with `CTRL-ALT-T`
3) Wait for build to be done
4) Dialog closes

Versions:
`atom-build: 0.53.0`

`$ atom-beta --version`
`1.5.0-beta0`

`$ uname -a`
`Linux 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 GNU/Linux`

**Comment by noseglid** [comment]
I think this is when the panel closes closes it closes all panels. Definitely worth looking into to see if this can be fixed, but I think it is atom that does it when a panel (`BuildView` is closed).

**Comment by noseglid** [comment]
I found the reason for this. It's actually when `atom.views.getView(atom.workspace).focus();` is called when detaching the build panel after a successful build. It makes sense that it closes the targets view at this point - but unfortunate behavior in OPs described use case.

We reset the focus to the workspace because we "steal" it when opening the build panel (so that `Esc` can be pressed to terminate the build).

I'm thinking the best solution to this would be to only focus the workspace if `this` (i.e. the build panel) is in focus right now. Otherwise the user has made some other focus selection and we should honor that.

**Comment by noseglid** [comment]
Easier than I though. Feel free to checkout #333 if you wanna test it before the next release.
