### ISSUE TITLE
.atom-build.json - No Eligible Build Targets

### ISSUE THREAD

**Issue by flyinbutrs** [noseglid/atom-build#310]
This is probably user error, but I can't tell from the docs how to make this work. I have a very basic .atom-build.json in the root of my git repo. Here are the contents:

```
{
  "cmd": "gem build mygem.gemspec; gem install *.gem; rm -f *.gem",
  "name": "mygem",
  "sh": true,
  "cwd": "{PROJECT_PATH}"
}
```

How can I make this be detected / run?

**Comment by noseglid** [comment]
You need to open Atom so that it is in your project root. Press `ctrl/cmd-shift-o` select the folder which contains your `.atom-build.json`.

**Comment by flyinbutrs** [comment]
Just to add a note, for some reason, this isn't always detected properly. And definitely adding a new one while atom is running isn't detected.  Overall, though, you were correct. :+1:

**Comment by noseglid** [comment]
If you add a new file you have to run `Build: Refresh Targets` (which can be run at any time you feel there are inconsistencies :smiley: )

**Comment by SubZane** [comment]
I still get this error, many times. I have ONE project open and I cannot find anywhere where that "Build: Refresh Targets" is located in the menu. 

Please help :)

**Comment by flyinbutrs** [comment]
check the command pallette (command + shift + P)

**Comment by SubZane** [comment]
great! thanks!

On Tue, Feb 23, 2016 at 6:42 PM Daniel Rosenbloom <notifications@github.com>
wrote:

> check the command pallette (command + shift + P)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noseglid/atom-build/issues/310#issuecomment-187810625>
> .
>
-- 
--

Best regards,
Andreas Norman
0709*

**Comment by nathancarter** [comment]
Where is "Build: Refresh Targets" documented?  I followed the instructions for creating a basic build file, and tinkered for some time, re-read docs for some time, googled for awhile, until I ended up at this issue that solved my problem.  I would think that "create a build config file in atom, then hit Cmd+Shift+B" is a really common workflow for a new project, and thus one that everyone would expect to succeed, but it doesn't due to this gotcha.  Perhaps the "No Eligible Build Targets" error should try running Refresh Targets for you before giving up?

**Comment by noseglid** [comment]
You're right, it's an outfall from where atom-build previously *always* refreshed target when pressing <kbd>cmd-alt-b</kbd> - which was removed because some providers are slow (especially those running a command for listing targets and then parsing the result).

It would make a lot of sense to run Refresh automatically when attempting to build **if** no targets exists. Would you mind creating a new issue for this?

**Comment by nathancarter** [comment]
OK no problem.

**Comment by nathancarter** [comment]
Done; see above.
