### ISSUE TITLE
Automatically build on save & Automatically save on build don't play nice

### ISSUE THREAD

**Issue by sardonicpresence** [noseglid/atom-build#324]
With both the 'Automatically build on save' and 'Automatically save on build' options enabled, with multiple modified files, saving one of them triggers a build, which triggers saving the others (which is good), which then triggers further builds that run alongside the first (which is bad), all sending output to the build pane.

**Comment by noseglid** [comment]
I see. I am not sure what the correct course of action is here.

One option would be to simply not trigger builds on when the save was issued by another build. However that seems like very unexpected behavior and will likely throw a lot of users off.

Not allowing both at the same time? Possibly.

Maybe it should just be a recommendation not to keep the on simultaneously. Some may configure the build tool to handle the case where it is triggered multiple times.

Delaying a the build for an arbitrary time to see if any other saves come in which may trigger the build and bundle them up? This will make the normal case bad in order to handle an edge case. Not good.

**Comment by sardonicpresence** [comment]
What about a special-case where, in the event of both settings being enabled, all files are saved first (knowing that a build is coming) then a single build triggered?

Not especially elegant but it would certainly be the option I would use and would not negatively affect the other modes.

An alternative would be to have successive builds kill prior ones so that only the most recently executed build runs. This would be particularly intuitive when older builds are no longer outputting to the build pane (which happens if you manually trigger a build). Not sure if this is a) possible or b) likely to play havoc with build tools though.

**Comment by sardonicpresence** [comment]
Though the more I think about it, the more I feel I'm being foolish as simply setting only save-on-build and building rather than saving accomplishes the same goal (where using build-on-save and save-all does not, at least with a naive build tool).

Perhaps no action is required at all, though evidently I did view the behavior as a bug at first.

**Comment by noseglid** [comment]
Yes, I've looked a bit a this, and I think the absolute best solution is to just do `save-on-build` and initiate a build, rather than initiating a save.

Thanks for the report!
