### ISSUE TITLE
Copy text

### ISSUE THREAD

**Issue by sdepold** [noseglid/atom-build#34]
Hi :)

first: Thanks for this great plugin. It's pretty nice!
One thing that could it make even more awesome is the capability to select and copy text from the output pane. When I run a build and it fails I'd like to be able to select parts of the output and hit `cmd+c` (copy shortcut) and paste the result somewhere else. While I can select text, it won't let me copy the text.

I'm not entirely sure if this is an issue with this plugin though.

**Comment by noseglid** [comment]
Glad you're enjoying it!

Hmm, I can copy text on Linux (since selecting text puts it in the clipboard). However, CTRL+C does not work. I'm guessing this is a bug.. looks like the same thing is described here: https://github.com/tcarlsen/atom-message-panel/issues/24

I'll have a look at that and try to add the necessary classes for CTRL+C to work. Thanks for your report!

**Comment by noseglid** [comment]
This is fixed and published in `v0.23.1`. Thanks again for your report!

**Comment by sdepold** [comment]
Yeah :) thanks a lot!
