### ISSUE TITLE
[Feature request] Improve the terminal output

### ISSUE THREAD

**Issue by marmistrz** [noseglid/atom-build#350]
GCC 5.x uses a colorful output which makes it much easier to read the error messages. Besides, the white-on-black terminal doesn't play nicely with light themes - it would be great to be able to configure the look of the terminal.

**Comment by noseglid** [comment]
You can disable the "white-on-black" which is the default via a configuration. Then the theme will pick the colors. If you want even further customizations, you can edit your personal stylesheet to your liking.

GCC 5.x (and any other tool outputting ANSI escape sequence - colors) will likely not do so because it's not really a TTY it's running in. Many CLI tools will check for a tty and only do rich output (such as colors) if it is available.

Often there are flags for toggling this behavior. Check the [man pages of gcc](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Language-Independent-Options.html)
