### ISSUE TITLE
Add support for multiple build commands

### ISSUE THREAD

**Issue by sryze** [noseglid/atom-build#37]
It would be great if we could define multiple build commands in `.atom-build.json` instead of just one. This would allow e.g. creating separate bindings for different commands, like `make` and `make test`.

I've seen something like this in [SciTE](http://www.scintilla.org/SciTE.html) where you can assign numbers to different commands and then use `Ctrl+N` to trigger command `N`.

**Comment by noseglid** [comment]
Cool idea. I really like it.

Maybe it should be possible to extend the `.atom-build.json` file with a keymap where the value is the same structure as the `.atom-build.json` is defined to be today. That way we could have different environments and arguments and all the goodies available in the plugin today.

**Comment by AngelEzquerra** [comment]
This could also be used to create a "run" command in addition to a "build" command.
Ideally, you should be able to also define a separate key combination for each such command.

**Comment by austinbirch** [comment]
I’ve just started using Atom, found this package, and then needed the ability to specify multiple builds. I hacked something together, but not sure whether this is the sort of the implementation you would like?

Here’s my changes: https://github.com/austinbirch/atom-build/compare/multiple-build-commands

If this is the sort of thing you are looking for, I’d be happy to add tests, make any changes, and submit a pull request.

**Comment by noseglid** [comment]
@austinbirch I really like what you're proposing!

Some notes which I may not have thought all the way through:
  * You're reading the `.atom-build.json` when the package is activated (which for most users is when Atom starts). Would it be good to re-read that file,

**Comment by austinbirch** [comment]
@noseglid Thanks for the feedback!

First reaction to your notes (also not thought all the way through!):

> Maybe we should have another file name than .atom-build.json for the named builds.

I think I’d prefer having one file that defines all builds, though I’m not sure what the best implementation here is. In my changes I’ve allowed the `.atom-build.json` to define an array of builds, though it feels a little odd to allow both a single object and an array in that config file.

The problem I’m seeing with using an array is that I’m not sure what the `build:trigger`, `build:confirm`, `build:no-confirm` actions should do in this case (in my changes, I’ve just allowed a user to specify a "default" that is used for those commands. This is not a great solution, because you could theoretically define more than one build as the default).

Not sure how open you would be to changing the format of the config file, but perhaps it could be something like below.

```
{
   "default": "name1",
   "otherBuildsSettingHere": "value",
   ...,
   "builds": {
       "name1": {...build config...},
       "name2": {...build config...}
   }
}
```

This config would allow properties to be described about the build process as a whole, and about individual builds. It’s also a flexible format for future changes, though it does force all builds to be named (not sure that’s very painful for the user though).

> You're reading the .atom-build.json when the package is activated (which for most users is when Atom starts). Would it be good to re-read that file every so often?

I think this is a good idea, however I’m not sure what the best implementation for this is, as I’m not familiar with the Atom API yet. Any suggestions on this?

> Should it be left to the user to configure keymaps or should we make an attempt at that?

It depends on workflow a bit I suppose. I’m planning on committing an `.atom-build.json` config to a repository with multiple contributors, and I wouldn’t want to force others to use the same keybindings as me (though we want the build configs to be shared).

If the users’ workflow is different it may make sense to have keybindings defined within `.atom-build.json`, so maybe a flexible option could be allowing an optional keybinding to be defined within the build that could be overridden by individual users if they wanted to use something different.

**Comment by noseglid** [comment]
I agree with you that keeping `.atom-build.json` even for named builds. I like the structure you proposed, but maybe the top level should be as it is today (to keep backwards compatability, and give the default build, e.g `build:trigger` meaning):
```json
{
   "cmd": "cmd for default build",
   "args":[  "args", "for", "default", "build" ],
   ...,
   "builds": {
       "name1": {...build config...},
       "name2": {...build config...}
   }
}
```

an example could be
```json
{
  "cmd": "gcc main.c -o main",

  "builds": {
    "warn": {
      "cmd": "gcc -Wall -Werror main.c -o main"
    },
    "test": {
      "cmd": "gcc test.c -o test && ./test"
    }
  }
}
```

Default it would build `main.c` to `main`. By building `warn` it would add some flags, and `test` would build the test program and run it.

With this in place, `cmd-alt-b`/`ctrl-alt-b` would trigger the default build specified in the top level of the object (for backwards compatibility). 
To trigger any other build, one would press `cmd-alt-p`/`ctrl-alt-p` and type the name of that build which would be mapped to the atom trigger `build:<name>`. Thoughts?

Re-reading the config could be done as a menu item triggered manually by the user, I suppose. I'm not sure we want to poll the file-system. Possibly we could set up a watch on `.atom-build.json` and re-read it every time it is changed using [fs.watch](http://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener).

Regarding keymaps, we could enhance on this further later on, but right now it doesn't seem like such an important thing.

**Comment by austinbirch** [comment]
I think the structure you’ve outlined there is great, it keeps backwards compatibility and makes sense with regards to default builds. It will fit well with a lot of projects too, as there will be generally a build-all command (top-level default in this structure), and then builds for sub-components. For example, a project I’m working on at the moment has a `buildBackend.sh` script, a `buildApp.sh` script, and finally a `buildAll.sh` script that incorporates the other two scripts.

I think your idea for the UI to trigger a named build is good too, and it still allows users to setup their own keybindings for named builds.

For re-reading the build config I think that a manually-triggered menu item would be good enough for now, as build configs probably do not change too often. Any time you make an adjustment you could just manually trigger a refresh of the config.

I also agree that keybindings can be left out for now. As long as the commands are easy to bind keys to, it is not that painful for a user to get the setup that they want.

I think that’s enough to go on for now. I’ll make the changes, add some tests, and then submit a pull request.

Thanks again for your feedback on this.

**Comment by noseglid** [comment]
Cool. I'm looking forward to what you come up with!

**Comment by noseglid** [comment]
Just a heads up, I made som changes on master which modularizes the build tools a bit. The way it finds the build command and all data structures are the same, just a change in code layout. I may impact what you're doing a bit.

**Comment by kankaristo** [comment]
Most IDEs have "targets" instead of named builds.

You always have the same keybinding for building, and you just change the active "target" to be built.

With targets, ```ctrl-alt-b``` would always be "Build" and another keybinding would bring up a list of targets  to choose between (or switch to the next target).

For example, if you have a separate targets for:
 - Linux debug
 - Linux release
 - Android debug
 - Android release
 - Run tests
 - Generate documentation
 - ...

... it would be nicer to just select the "active" target and press ```ctrl-alt-b``` to build, instead of typing out the target's name every time you build.

Of course, this could be used in addition to named builds, i.e. building the latest named build (active target) by default.

**Comment by anion155** [comment]
wont it be simpler to support .sublime-build? There are default setting for every build system and "variants" array.

**Comment by anion155** [comment]
And yeah, as you using json format for "builds" you better use array:
````json
"builds": [
  {
    "target": "target_name",
    "cmd": "target_cmd"
  },
  {
    ...
  }
]
````

**Comment by noseglid** [comment]
@austinbirch Any updates on this?

**Comment by austinbirch** [comment]
@noseglid Sorry for the delay, became busy at work and mostly switched back (mostly) to emacs.

I have a pretty stable initial implementation of what we had discussed originally on this branch here https://github.com/austinbirch/atom-build/tree/multiple-build-commands. 

I’d also like to look the "target"-based suggestions that have been made, to see if there’s a neater solution (do you have any thoughts on those suggestions?)

I’ll see if I can get some time in the next few days to finish this stuff up.

**Comment by SubZane** [comment]
+1 on this. I'd really like to see this implemented.

**Comment by noseglid** [comment]
@austinbirch Would you mind if I pushed your changes to noseglid/atom-build on a development branch. We could collaborate to get this change finished on that branch. I would love to see this feature included as soon as possible :)

**Comment by austinbirch** [comment]
@noseglid Yes, that could be a good idea. I’ve pushed an updated version of that multiple-build-commands so that it’s up to date with master, plus a couple of bug fixes.

I’ve also written and published a [build-targets](https://github.com/austinbirch/atom-build/tree/build-targets) branch (doesn’t have tests yet). That branch contains an implementation of "targets" (following @kankaristo's suggestion), which allows you to select an "active target" from a list (pulled out of the tools config in a similar way to what we have discussed above), and provides a keybinding for building the "active" target. A disadvantage of might be that it doesn’t (yet) support keybindings for named targets.

I prefer the targets-based approach (I think it’s a simpler idea), so it would would be great if you could take a look at that implementation too.

**Comment by noseglid** [comment]
@austinbirch I did some work on this. You've done an excellent job so far.

I got this idea, if the build tool gave the list of all named builds, then `Grunt`, `gulp` or `Make` could provide all it's targets as named builds. This would be a neat addition to just having it for the custom build file. I'm half-way through implementing it. What do you think?

**Comment by austinbirch** [comment]
That sounds good, though (unless I’m misunderstanding) I think that’s similar to how I’ve implemented it in the [build-targets](https://github.com/noseglid/atom-build/compare/master...austinbirch:build-targets?diff=unified&expand=1&name=build-targets) branch (which I think should be the preferred implementation)?

If the "tool" returns a settings object that has a targets property, it will already get it’s named targets added to the list of available targets. You can see this behaviour [here](https://github.com/noseglid/atom-build/compare/master...austinbirch:build-targets?diff=unified&expand=1&name=build-targets#diff-26b681bd4dac10f25d5293c7595c435bR149).

**Comment by noseglid** [comment]
Cool, I see. I didn't take a good look on that branch yet, but it seems I've duplicated some of that work on my local branch :disappointed: . I agree this should be the preferred implementation.

Though, I thought the selection of the active target could be last built target. So if you select a target from the `SelectListView` it will also mark that target as active, causing all subsequent build triggers (`ctrl-alt-b` or `cmd-alt-b`) to build that target.

**Comment by austinbirch** [comment]
That’s pretty similar to how it works now also, except that it is behind another command (`build:build-active-target` vs `build:trigger`). I could combine these two commands so that `build:trigger` builds the active target if selected, and has the current behaviour if there is no active build selected?

**Comment by noseglid** [comment]
I think the work-flow is more natural if we just add one command for setting the active target, and the current `build:trigger` works as familiar. That way, users wont have to learn a new key-combination - and the `build`-package is less likely to collide with other bound key combinations.

I'll push my changes later today to [noseglid/atom-build#dev/multiple-build-commands](https://github.com/noseglid/atom-build/tree/dev/multiple-build-commands) which is where I think we should keep all progress on this to not accidentially implement same things twice again :)

**Comment by austinbirch** [comment]
Okay sounds good. Is that branch based off of the changes in my [multiple-build-commands](https://github.com/austinbirch/atom-build/tree/multiple-build-commands) branch?

Unless you have other work you want to keep in that branch, it might actually be worth basing off of my [build-targets](https://github.com/noseglid/atom-build/compare/master...austinbirch:build-targets?diff=unified&expand=1&name=build-targets) branch, as it will only be a couple of line changes & some line removals to make `build:trigger` build the active target. I think the implementation in that branch is much better. I could make those changes today (and open a PR if you want), then the only thing that would need to be added is some tests.

**Comment by noseglid** [comment]
I did some other changes as well, such as [kebabCasing](http://c2.com/cgi/wiki?KebabCase) custom build commands and automatically observe changes to the `.atom-build.json` file for updating named builds. It might still be better though, I'lll have a look when I have sometime later today.

If you have time to complete those changes that'd be great. Would give me a neater base to work off.

**Comment by noseglid** [comment]
As I said in #77, I continued the work on your stuff. It's pushed to noseglid/atom-build@dev/build-targets.
I have done this so far:

  * Changed the keybinding to `cmd-alt-t`/`ctrl-alt-t`.
  * Automatically trigger a build when a target is selected.
  * Made `tool.settings` asynchronous so we can do more stuff before determining targets for a build tool.
  * Implemented parsing of targets for `Grunt`. The others should be fairly easy now.
  * Prepended the name in the SelectListView with the tool.

Left to do:
  * Write tests.
  * Implement target parsing for at least `gulp` and `Makefile`.

Another cool thing with this, it is now possible to have multiple build tools running at the same time. For instance having `gulpfile.js` with all project specific builds, and then one very custom target in `.atom-build.json`  which might be local to one developers environment. And it's seamless to switch between them.

**Comment by noseglid** [comment]
I wrote a couple of specs:

 * should list those targets in a SelectListView (from .atom-build.json)
 * should list those targets in a SelectListView (from Gruntfile.js)
 * should list those targets in a SelectListView (from gulpfile.js)
 * should mark the first target as active
 * it should run the selected build
 * it should run the default target if no selection has been made
 * run the selected target if selection has changed, and subsequent build should run that target

@austinbirch Any other tests you can think of which would be suitable?

**Comment by noseglid** [comment]
I have merged this to master. It will be included in the next release `v0.36.0`. Yay. Thanks for input and cooperation.

I decided not to include Makefile extraction as it's really difficult to only get "relevant" targets. There are a lot of targets generated by Make per default and knowing which ones are real and which ones the user would rather not see is a pickle.

**Comment by sryze** [comment]
Great! I have one question though, in regards to Grunt: why is it choosing the first target? Shouldn't it choose the `default` target initially?

**Comment by noseglid** [comment]
Yes it should. There is also a [test for this](https://github.com/noseglid/atom-build/blob/master/spec/build-targets-spec.js#L65-L89). Are you saying it doesn't?

**Comment by sryze** [comment]
It seems so, it runs a `copy` target when I first open the project, which goes first in the buld targets list. If I switch the target to `default` it works okay.

**Comment by sryze** [comment]
There seems to be a bug in the task sorting function in Grunt.js, I managed to fix that by replacing

```javascript
return ('default' === t1) ? -1 : t1.localeCompare(t2);
```

with:

```javascript
return [0, -1, 1][[t1, t2].indexOf('default') + 1] || t1.localeCompare(t2);
```

at line 43.

**Comment by triaglesis** [comment]
Hi guys, what is the latest template for multiple targets? I can't find an example and just trying to make list from each cmd target.

**Comment by noseglid** [comment]
If you [specify a custom build command](https://github.com/noseglid/atom-build#specify-a-custom-build-command) then you can have a `targets` property which should be an array.

Example in yml
```yml
targets:
  someTarget:
    cmd: "echo"
    args:
      - stuff
  someOtherTarget:
    cmd: make blabla
```

**Comment by triaglesis** [comment]
Hooray! Thanks, it's just as yml I understand.
Will add working example for anybody like me:

![image](https://user-images.githubusercontent.com/12595699/29399678-d5eea38a-8332-11e7-88df-20f8df446bb6.png)
