### ISSUE TITLE
value.replace is not a function

### ISSUE THREAD

**Issue by xgdgsc** [noseglid/atom-build#405]
I got an error `value.replace is not a function` with atom-build-make. How can I debug this?

**Comment by noseglid** [comment]
Where and how do you get this? Is there a stacktrace?

**Comment by xgdgsc** [comment]
I just run the build project command and it shows the warning popup without a stacktrace, which is unusual.

**Comment by xgdgsc** [comment]
May have been caused by conflicts with other packages, fine now.

**Comment by Deimos28** [comment]
I get the same error: I'm using Atom to edit Elm files. Got a .atom-build.yml file containing

cmd: make

**Comment by noklesta** [comment]
I initially got the same error with .atom-build.yml just containing `cmd: echo Hello world`, but restarting Atom fixed it.

**Comment by noklesta** [comment]
It turns out that this happens when `process.env` contains values that are not strings. In my case those are the values of `ELECTRON_NO_ATTACH_CONSOLE` and `ELECTRON_RUN_AS_NODE`, which are both set to the number 1. 

In line 134 of build.js, each environment value is sent to the `replace` function defined in utils.js, which fails when it tries to call `.replace` on these numbers in line 55 of that file.

I am running `elm make` as my build command, and the problematic environment values are only set when the build fails (but after a failed build, they stick around and continue to cause the exception even if the Elm source is corrected). 

I am running Atom 1.8 on Mac. 

@xgdgsc perhaps you would like to re-open the issue?

**Comment by noseglid** [comment]
@noklesta Thanks for the detailed report.

I think we should add a guard at the beginning of the `replace` function and only the replacements if `typeof value === 'string'`.
