### ISSUE TITLE
Integrate with busy-signal

### ISSUE THREAD

**Issue by steelbrain** [noseglid/atom-build#421]
[`busy-signal`](https://github.com/steelbrain/busy-signal) is a base Atom package that allows it's consumers to indicate to the user that something is happening. It has an easy to use [`API`](https://github.com/steelbrain/busy-signal/wiki/Busy-Signal-API).

The main benefit of using it is that it'll make your own codebase cleaner while providing a unified place for users to see if something is happening.

**Comment by noseglid** [comment]
It's funny. We had the same idea. I'm actually working on something similar right now: https://atom.io/packages/busy

It's not ready yet, but I'll be looking to use that instead

**Comment by steelbrain** [comment]
Any particular reason of having two packages? We could both collaborate on one

**Comment by noseglid** [comment]
Not really no. I had just thought about for a few weeks and wanted to follow through :)

**Comment by steelbrain** [comment]
Great, I've given you push access to the `busy-signal` package, which also means publish access on APM. Lets collaborate on just one :)

**Comment by danielbayley** [comment]
@noseglid @steelbrain So what happened here in the end?

If I have _build_ and _linter_ installed (as many probably do) I have all this extra stuff clogging up the status bar…

**Comment by mangecoeur** [comment]
Same issue, bit distracting...

**Comment by rapgenic** [comment]
I'm quite sorry for doing this, but since there are still two different packages, and I need my working environment as clean as possible, I created two bridge packages, which pretend to be `busy` or `busy-signal`, but actually just call the other one's API.

- [atom-busy-unifier-ng](https://github.com/rapgenic/atom-busy-unifier-ng) for whom wants only @noseglid busy
- [atom-busy-unifier-sb](https://github.com/rapgenic/atom-busy-unifier-sb) for whom wants only @steelbrain busy-signal

I hope they soon won't be useful anymore, and will be replaced by a single `busy` package :)

But for now, they should be useful to resolve the clogging problem...
 
They should work well, but I didn't have enough time to test them thoroughly, so any feedback or bug report is welcomed :)

**Comment by laughedelic** [comment]
It's been almost a year. Do we really need two packages and two icons in the status bar? Please, guys, just join your forces, I think users mostly don't which one to use, but having both is inconvenient (and @rapgenic's workaround is not a real solution).

**Comment by jonyeezs** [comment]
I actually prefer to have two icons.
busy-signal to show processes that end automatically

and busy to show long pending processes that may require human intervention to end
