### ISSUE TITLE
Problem on using build -- cannot even use it

### ISSUE THREAD

**Issue by AdrianSoMC** [noseglid/atom-build#536]
There is a problem here
![default](https://user-images.githubusercontent.com/31738652/30436991-1cd82130-99a0-11e7-95d0-364b06f46f94.png)
As seen from above picture, when I press f9
It just cannot compile and run a python code
(I have already installed build-python thing)
![default](https://user-images.githubusercontent.com/31738652/30437094-5bc4c83a-99a0-11e7-812d-10cebc8b5961.png)
It just doesn't allow me to even select target

**Comment by oli-obk** [comment]
Have you tried opening atom on the directory your file is in?

**Comment by AdrianSoMC** [comment]
Sorry, what do you mean by opening it on the directory my file is in?

**Comment by oli-obk** [comment]
Instead of rightclicking a file and choosing "open with atom", rightclick the containing directory. You might need to enable context menu entries in atom's settings

**Comment by noseglid** [comment]
What @oli-obk said. `atom-build` is focused around building projects. not individual files. You need to open a directory.

Now arguably this is weird for the python provider since it doesn't necessarily require a project. We might be looking to change that.

But for now, you need to open a directory (so you can see the tree view).
