### ISSUE TITLE
No eligible build target. No configuration to build this project exists.

### ISSUE THREAD

**Issue by kojihirai** [noseglid/atom-build#543]
In Atom when I press F9 to compile/build the project I get this error.
Can someone help me? 
![image](https://user-images.githubusercontent.com/17133941/31701836-e0a5f140-b387-11e7-9316-032b60750ba2.png)

**Comment by noseglid** [comment]
Have you followed the configuration detailed in the README?
You have to provide more info. What does your project look like? Do you have providers? Configuration (`.atom-build.*`-file)?

**Comment by borishere** [comment]
I have this issue now. In 2017 I built scss files with `build-sass` package and everything was fine. 
Also I don't see the build target name in the bottom left corner on the status bar.

**Comment by jimkernsjr** [comment]
I started out with such high expectations for platformio, and it's been nothing but a disappointment.  It seems nothing works as it should.  I followed the instruction to a T to install it, put the appropriate build platforms and board on, and loaded a project I wanted to work on that was built in Platformio.  First, it seems I dont have the right build platform selected - see status bar where it says "Photon" and "no device selected::
![screenshot from 2018-04-14 19-30-50](https://user-images.githubusercontent.com/26207370/38773528-de2980b8-401c-11e8-8db1-2a6c8a1406e1.png)
So I try to change it, but espressif8266 is not available even so it's installed:
![screenshot from 2018-04-14 19-50-50](https://user-images.githubusercontent.com/26207370/38773551-57610618-401d-11e8-80e2-f0818ab09614.png)
![screenshot from 2018-04-14 19-51-14](https://user-images.githubusercontent.com/26207370/38773552-58bd6b28-401d-11e8-8d4c-01c81e25e453.png)

So what's the problem?  I cant find a solution anywhere.
I assume it cant build (1st screenshot) because these aren't proper.  
I disabled the Particle addons, now everything looks worse:
![screenshot from 2018-04-14 20-03-53](https://user-images.githubusercontent.com/26207370/38773619-1183f52c-401f-11e8-9ff6-6d7c0099f121.png)
It will not let me "run other target" - it tells me no targets found.

Any ideas?  I dont see any help in the documentation that could reveal what is wrong.  Searching google reveals not much.

Thanks in advance.

**Comment by sarahana-hm** [comment]
Same issue, I can't run build-sass

**Comment by sarahana-hm** [comment]
same here, can't run build-sass

**Comment by VitandinBalulo** [comment]
Hi i have the same issue, I'm using it in a basic Arduino project, on Ubuntu 20.04 and at the beginning it worked very well, but now i have to use the Arduino IDE and I'd really rather to use Atom/ PlatformIO

What can I do if i installed it W/O the readme, just uninstall/ install again??  I followed the instructions of a video course.
IF SOMEONE ONE KNOWS HOW TO FIX IT PLEASE TELL US

THANKYOU
